### ISSUE TITLE
Usability for FHD

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#100]
![image](https://github.com/SebastianHanfland/RallyGPXMerger/assets/43017965/0707edb7-951b-4907-b09a-8ae3d6a20bf9) Let's adjust spacings for visibility.

**Comment by LeTaPe** [comment]
some more: 
![image](https://github.com/SebastianHanfland/RallyGPXMerger/assets/43017965/79a176c8-6270-4570-82db-afd9de258c36)

**Comment by LeTaPe** [comment]
another one: 
![image](https://github.com/SebastianHanfland/RallyGPXMerger/assets/43017965/72ae32a3-4cd3-405a-aa80-53459ae50cf8)

**Comment by SebastianHanfland** [comment]
@LeTaPe I think the most parts should be ok now, for other we can start new tickets
