### ISSUE TITLE
Links to Points on Map

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#102]
Luftlinie.org does not handle single points well, as they cannot be zoomed out. This mostly effects Pausenplätze & Knotenpunkte.

**Comment by SebastianHanfland** [comment]
@LeTaPe I think with [this commit](https://github.com/SebastianHanfland/RallyGPXMerger/commit/61c60524a32c77b0f9dabcda129c6be053f14d93) we can also close it
