### ISSUE TITLE
Disabling the visual representation of routes also removes sections

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#123]
![image](https://github.com/SebastianHanfland/RallyGPXMerger/assets/43017965/1ba5b9ce-2fb8-4b3c-978f-00191d24d744)
![image](https://github.com/SebastianHanfland/RallyGPXMerger/assets/43017965/2c5008cb-ecd1-4857-a8e9-44e5610413bb)

**Comment by SebastianHanfland** [comment]
@LeTaPe Is it possible that you had a filter active on the sections within the situation?
The map is also senstive to the filters that you apply in the sections as well as in the track.

The only thing, I can think of it to add numbers  like: Abschnitte (4 of 51) to represent the filter if there is any to not lead to confusion

**Comment by SebastianHanfland** [comment]
I added the display of the fraction. It is a bit slow, but I think the displaying of the routes based on the filter was anyways slow
