### ISSUE TITLE
Hovern auf Route friert gelegentlich ein

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#150]
Im present-Modus friert ab und zu eine hervorgehobene Route ein, sodass die anderen Routen auch bei einer Bewegung der Maus zunächst nicht sichtbar sind. Sobald man zufällig eine andere "unsichtbare" Route überhovert, ist alles wieder in Ordnung.
Der Auslöser kann nicht reproduzierbar ermittelt werden.
Eine Teil-Lösung besteht darin, alle nicht hervorgehobenen Routen etwas transparenter oder grau darzustellen, sodass man diese zumindest nicht als "fehlend" wahrnimmt.
Ansonsten wäre natürlich auch ein Fix des Glitches eine nette Sache.

**Comment by LeTaPe** [comment]
Vorzugsweise passiert es beim Scrollen oder wechseln auf die Oberfläche mit dem Slider. Beides ist nicht deterministisch reproduzierbar.

**Comment by LeTaPe** [comment]
Auch die Vergleichsansicht ist betroffen.

**Comment by LeTaPe** [comment]
Beim Ausblenden einer Variante deren Zug eingefroren ist, erhält man eine leere Karte, bis auf Wiedereinblenden nicht nutzbar ist.

**Comment by SebastianHanfland** [comment]
Ich habe jetzt die restlichen Routen auf 0.2 opacity gesetzt. Gerne beobachten
