### ISSUE TITLE
Displaying break points differently

### ISSUE THREAD

**Issue by SebastianHanfland** [SebastianHanfland/RallyGPXMerger#62]
Identifying via time difference, use another symbol, to make it clear what happens, maybe toggle them separately

**Comment by SebastianHanfland** [comment]
It should also be nice, to add information about the breaks if there are toilets available or not.

**Comment by SebastianHanfland** [comment]
@LeTaPe Now the Node points, where routes come together are not displayed anymore, but I think it is ok, therefore only the break points are displayed.
Do you think this is ok?

**Comment by LeTaPe** [comment]
I agree. Maybe I missed something, but in this case, we can reopen the issues.
