### ISSUE TITLE
"On map" icon in "street resolver" broken.

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#78]
By Pressing the "on-map" icon newt to the respective street name in the street-resolver-tab, I want the respective street on the map to be shown. Right now, nothing happens. Open question: How do we deal with the map being on a different tab, as going back to the street resolver does not lead to the same spot in the table?

**Comment by SebastianHanfland** [comment]
I removed this, because it does not make any sense with the current UI

**Comment by SebastianHanfland** [comment]
I added the external link again, that should be helpful to further look the unknown up
