### ISSUE TITLE
Colors of Variants

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#85]
I want to see the bike icons from the simulation output in the version-specific color.
The bike icons should also dis-/reappear with the (de-)selection of the variants.
I want to recognize the version-specific colors from the variant selector at the top without compromizing the readability of the Variants name.

**Comment by SebastianHanfland** [comment]
@LeTaPe I think the features are now available, if you also think you, please close the ticket, or provide feedback
