### ISSUE TITLE
.xlsx export

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#89]
I want to automatically create well-formatted tables.
The format needs to be discussed.
The implementation can either be part of the web app or a seperate ".csv-Data + .xlsx-Template -> formatted Table" converter.

Missing entries are:
Breaking points
Crossing points
Train crossings?
Names and contact data of the local guides.

**Comment by SebastianHanfland** [comment]
@LeTaPe I assume that we do not need this anymore now with the pdf export, right? Only train crossings is an open point
