### ISSUE TITLE
Consistent Timing Between Simulation and Street Output

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#92]
Right now, we have a discrepancy of roughly 5-10 min between the simulation tool and the street output.
A9 is one example:
[v3_mitPause2.json](https://github.com/SebastianHanfland/RallyGPXMerger/files/13861101/v3_mitPause2.json)

![image](https://github.com/SebastianHanfland/RallyGPXMerger/assets/43017965/ff2d1ce2-3e11-4ca7-96af-cc5a6b72a8e3)
![image](https://github.com/SebastianHanfland/RallyGPXMerger/assets/43017965/dc8dae6d-6cfd-40ea-9b51-41cdc713e05d)

**Comment by SebastianHanfland** [comment]
@LeTaPe Thank you for spotting this. I checked it today, and it seems like there were already some adjustments in the last month. It now shows consistently and I also found a small mismatch. While aggregating, the first point of the next street is now also taken into account which leads to better fitting times.
